### PR TITLE
Update Landing Page

### PR DESCRIPTION
**Pull request by Aquingel**
- Changed the hero shot
image

- Replaced the assets (logo .png files, hero-bg .jpg)

- Removed the pointed finger, and realigned the email banner contents
image

### CODE REVIEW

**Comment by Carryl21** [comment]
HI, CG! I think it is much better ipashort nato ni: 
image

Taas ra kaayo sya hihi

**Comment by Carryl21** [comment]
And padak-an ag height.

**Comment by Aquingel** [comment]
Gotcha, Carryl!

**Comment by Aquingel** [comment]
- Decreased width, increased height
- Replaced footer logo with a higher definition one.
image

**Comment by Carryl21** [comment]
Nice! Thank you, CG!

**Pull request merged**
