### PR TITLE
Sample file structure of the server folder

### PR DESCRIPTION
**Pull request by Carryl21**
Hello! I created a sample file structure for the server folder. I'm not sure if this is right. Pls ko check po. Btw, don't merge this to main. I just raised this pr for you guys to be able to properly see and evaluate the file structure. 

Here's the list of the folders involved. 
image

1. Here's the example codes inside the server. 
image

2. The route folder holds the file that consists all the api routes. Here, the main functionality of the said api route is gibutang sa controller folder. 
image

3. The controller folder holds the main functionality of the api routes. 
image

4. Here, the database folder, model folder, and middleware folder is empty pa.  But basically, the database folder holds the file that connects to the database, the model folder holds all the database schema, and middleware folder holds all the middleware that we'll use here. 
image

5. Btw, I also added the dotenv here (for simple separation of secrets). However, that is a dev dependency and must not be included in the production. 
image

### CODE REVIEW

**Comment by Carryl21** [comment]
Also, give a comment about this guys so that we can finalize the file structure of the server folder.

**Comment by Aquingel** [comment]
Hi Carryl! Comprehensive rajud imong pagstructure sa folder, and I'm G with this ra.

A personal minor point of consideration ra siguro is the naming of folders, like the route and controller folders could be renamed as 'api-route' and 'api-controller', that way in file navigation, easier sya since both of these folders refer to api routing. However, it's not that necessary since the folders are not that excessive, and memorable raman sad ang names, so G rajud as is.

That's all for me. I'm taking your lead right now since you're hard carrying front end jud (Thank you very much!!!!!!) 

When I become more competent with our work, I will have more concrete opinions.

**Comment by AmGthrow** [comment]
I'll merge this into my fork so I can start refactoring. Question lang on the middleware, doesn't that part get setup in `server.js` instead of `/middleware`? We're already `app.use()`-ing when we set up the app

**Comment by AmGthrow** [comment]
Moved my server code into this file structure na, just hoping for clarification on this bit about middleware mounting https://github.com/AmGthrow/CMSC128C/pull/50/files#r833851661

**Pull request merged**
